/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DifficultyLevel = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const ResourceStatus = IDL.Variant({
  'deleted' : IDL.Null,
  'active' : IDL.Null,
  'inactive' : IDL.Null,
  'archived' : IDL.Null,
});
export const NationTime = IDL.Record({
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
});
export const QuestionType = IDL.Variant({
  'shortAnswer' : IDL.Null,
  'fillInTheBlanks' : IDL.Null,
  'multipleChoice' : IDL.Null,
  'trueFalse' : IDL.Null,
});
export const Question = IDL.Record({
  'marks' : IDL.Opt(IDL.Nat),
  'status' : ResourceStatus,
  'topic' : IDL.Nat,
  'difficulty' : IDL.Opt(DifficultyLevel),
  'explanation' : IDL.Opt(IDL.Text),
  'createdAt' : NationTime,
  'text' : IDL.Text,
  'correctAnswer' : IDL.Nat,
  'questionType' : QuestionType,
  'updatedAt' : NationTime,
  'questionId' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const ContentInput = IDL.Record({
  'title' : IDL.Text,
  'subjects' : IDL.Nat,
  'order' : IDL.Nat,
  'difficulty' : DifficultyLevel,
  'description' : IDL.Text,
  'classId' : IDL.Nat,
  'durationMinutes' : IDL.Nat,
  'pdfUrl' : IDL.Opt(IDL.Text),
  'questions' : IDL.Vec(Question),
  'videoUrl' : IDL.Opt(IDL.Text),
  'textContent' : IDL.Opt(IDL.Text),
});
export const AdminStats = IDL.Record({
  'topicsCompletedTotal' : IDL.Nat,
  'totalStudents' : IDL.Nat,
  'activeToday' : IDL.Nat,
});
export const Chapter = IDL.Record({
  'id' : IDL.Nat,
  'status' : ResourceStatus,
  'title' : IDL.Text,
  'order' : IDL.Opt(IDL.Nat),
  'icon' : IDL.Opt(IDL.Text),
  'createdAt' : NationTime,
  'classId' : IDL.Opt(IDL.Nat),
  'updatedAt' : NationTime,
  'subjectId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'classId' : IDL.Text,
  'languagePref' : IDL.Text,
  'medium' : IDL.Text,
});
export const CompletionStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const TopicProgressEntry = IDL.Record({
  'id' : IDL.Nat,
  'timeSpentSeconds' : IDL.Nat,
  'studentId' : IDL.Nat,
  'completionStatus' : CompletionStatus,
  'createdAt' : NationTime,
  'attempts' : IDL.Nat,
  'score' : IDL.Nat,
  'updatedAt' : NationTime,
  'correctAnswers' : IDL.Nat,
  'topicId' : IDL.Nat,
});
export const ProfileType = IDL.Variant({
  'teacher' : IDL.Null,
  'student' : IDL.Null,
  'parent' : IDL.Null,
});
export const StudentProfile = IDL.Record({
  'id' : IDL.Nat,
  'timezone' : IDL.Text,
  'grades' : IDL.Text,
  'country' : IDL.Text,
  'subjects' : IDL.Vec(IDL.Text),
  'displayName' : IDL.Text,
  'birthdate' : IDL.Text,
  'city' : IDL.Text,
  'userId' : IDL.Principal,
  'joinedAt' : IDL.Int,
  'profileID' : IDL.Text,
  'photoURL' : IDL.Text,
  'classId' : IDL.Nat,
  'email' : IDL.Text,
  'languagePref' : IDL.Text,
  'updatedAt' : IDL.Int,
  'state' : IDL.Text,
  'entrySource' : IDL.Text,
  'gender' : IDL.Text,
  'phone' : IDL.Text,
  'parentID' : IDL.Text,
  'profileType' : ProfileType,
  'deletedAt' : IDL.Int,
  'medium' : IDL.Text,
});
export const Topic = IDL.Record({
  'id' : IDL.Nat,
  'status' : ResourceStatus,
  'title' : IDL.Text,
  'order' : IDL.Opt(IDL.Nat),
  'difficulty' : IDL.Opt(DifficultyLevel),
  'createdAt' : NationTime,
  'description' : IDL.Opt(IDL.Text),
  'chapterId' : IDL.Nat,
  'classId' : IDL.Opt(IDL.Nat),
  'updatedAt' : NationTime,
  'durationMinutes' : IDL.Opt(IDL.Nat),
  'subjectId' : IDL.Nat,
  'pdfUrl' : IDL.Opt(IDL.Text),
  'questions' : IDL.Vec(Question),
  'videoUrl' : IDL.Opt(IDL.Text),
  'textContent' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChapter' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'createStudentProfile' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createTopic' : IDL.Func([ContentInput], [IDL.Nat], []),
  'deleteChapter' : IDL.Func([IDL.Nat], [], []),
  'deleteTopic' : IDL.Func([IDL.Nat], [], []),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAllChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
  'getAllClasses' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChaptersForSubject' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Chapter)],
      ['query'],
    ),
  'getMyProgress' : IDL.Func([], [IDL.Vec(TopicProgressEntry)], ['query']),
  'getMyStudentProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
  'getStudentProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(StudentProfile)],
      ['query'],
    ),
  'getStudentProgress' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TopicProgressEntry)],
      ['query'],
    ),
  'getTopicsForChapter' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Vec(Topic)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllStudents' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateChapter' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
      ],
      [],
      [],
    ),
  'updateStudentProfile' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateTopic' : IDL.Func([IDL.Nat, ContentInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DifficultyLevel = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ResourceStatus = IDL.Variant({
    'deleted' : IDL.Null,
    'active' : IDL.Null,
    'inactive' : IDL.Null,
    'archived' : IDL.Null,
  });
  const NationTime = IDL.Record({
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
  });
  const QuestionType = IDL.Variant({
    'shortAnswer' : IDL.Null,
    'fillInTheBlanks' : IDL.Null,
    'multipleChoice' : IDL.Null,
    'trueFalse' : IDL.Null,
  });
  const Question = IDL.Record({
    'marks' : IDL.Opt(IDL.Nat),
    'status' : ResourceStatus,
    'topic' : IDL.Nat,
    'difficulty' : IDL.Opt(DifficultyLevel),
    'explanation' : IDL.Opt(IDL.Text),
    'createdAt' : NationTime,
    'text' : IDL.Text,
    'correctAnswer' : IDL.Nat,
    'questionType' : QuestionType,
    'updatedAt' : NationTime,
    'questionId' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const ContentInput = IDL.Record({
    'title' : IDL.Text,
    'subjects' : IDL.Nat,
    'order' : IDL.Nat,
    'difficulty' : DifficultyLevel,
    'description' : IDL.Text,
    'classId' : IDL.Nat,
    'durationMinutes' : IDL.Nat,
    'pdfUrl' : IDL.Opt(IDL.Text),
    'questions' : IDL.Vec(Question),
    'videoUrl' : IDL.Opt(IDL.Text),
    'textContent' : IDL.Opt(IDL.Text),
  });
  const AdminStats = IDL.Record({
    'topicsCompletedTotal' : IDL.Nat,
    'totalStudents' : IDL.Nat,
    'activeToday' : IDL.Nat,
  });
  const Chapter = IDL.Record({
    'id' : IDL.Nat,
    'status' : ResourceStatus,
    'title' : IDL.Text,
    'order' : IDL.Opt(IDL.Nat),
    'icon' : IDL.Opt(IDL.Text),
    'createdAt' : NationTime,
    'classId' : IDL.Opt(IDL.Nat),
    'updatedAt' : NationTime,
    'subjectId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'classId' : IDL.Text,
    'languagePref' : IDL.Text,
    'medium' : IDL.Text,
  });
  const CompletionStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const TopicProgressEntry = IDL.Record({
    'id' : IDL.Nat,
    'timeSpentSeconds' : IDL.Nat,
    'studentId' : IDL.Nat,
    'completionStatus' : CompletionStatus,
    'createdAt' : NationTime,
    'attempts' : IDL.Nat,
    'score' : IDL.Nat,
    'updatedAt' : NationTime,
    'correctAnswers' : IDL.Nat,
    'topicId' : IDL.Nat,
  });
  const ProfileType = IDL.Variant({
    'teacher' : IDL.Null,
    'student' : IDL.Null,
    'parent' : IDL.Null,
  });
  const StudentProfile = IDL.Record({
    'id' : IDL.Nat,
    'timezone' : IDL.Text,
    'grades' : IDL.Text,
    'country' : IDL.Text,
    'subjects' : IDL.Vec(IDL.Text),
    'displayName' : IDL.Text,
    'birthdate' : IDL.Text,
    'city' : IDL.Text,
    'userId' : IDL.Principal,
    'joinedAt' : IDL.Int,
    'profileID' : IDL.Text,
    'photoURL' : IDL.Text,
    'classId' : IDL.Nat,
    'email' : IDL.Text,
    'languagePref' : IDL.Text,
    'updatedAt' : IDL.Int,
    'state' : IDL.Text,
    'entrySource' : IDL.Text,
    'gender' : IDL.Text,
    'phone' : IDL.Text,
    'parentID' : IDL.Text,
    'profileType' : ProfileType,
    'deletedAt' : IDL.Int,
    'medium' : IDL.Text,
  });
  const Topic = IDL.Record({
    'id' : IDL.Nat,
    'status' : ResourceStatus,
    'title' : IDL.Text,
    'order' : IDL.Opt(IDL.Nat),
    'difficulty' : IDL.Opt(DifficultyLevel),
    'createdAt' : NationTime,
    'description' : IDL.Opt(IDL.Text),
    'chapterId' : IDL.Nat,
    'classId' : IDL.Opt(IDL.Nat),
    'updatedAt' : NationTime,
    'durationMinutes' : IDL.Opt(IDL.Nat),
    'subjectId' : IDL.Nat,
    'pdfUrl' : IDL.Opt(IDL.Text),
    'questions' : IDL.Vec(Question),
    'videoUrl' : IDL.Opt(IDL.Text),
    'textContent' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChapter' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'createStudentProfile' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createTopic' : IDL.Func([ContentInput], [IDL.Nat], []),
    'deleteChapter' : IDL.Func([IDL.Nat], [], []),
    'deleteTopic' : IDL.Func([IDL.Nat], [], []),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAllChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
    'getAllClasses' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChaptersForSubject' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Chapter)],
        ['query'],
      ),
    'getMyProgress' : IDL.Func([], [IDL.Vec(TopicProgressEntry)], ['query']),
    'getMyStudentProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
    'getStudentProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(StudentProfile)],
        ['query'],
      ),
    'getStudentProgress' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TopicProgressEntry)],
        ['query'],
      ),
    'getTopicsForChapter' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Vec(Topic)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllStudents' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateChapter' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
    'updateStudentProfile' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateTopic' : IDL.Func([IDL.Nat, ContentInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };