/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'topicsCompletedTotal' : bigint,
  'totalStudents' : bigint,
  'activeToday' : bigint,
}
export interface Chapter {
  'id' : bigint,
  'status' : ResourceStatus,
  'title' : string,
  'order' : [] | [bigint],
  'icon' : [] | [string],
  'createdAt' : NationTime,
  'classId' : [] | [bigint],
  'updatedAt' : NationTime,
  'subjectId' : bigint,
}
export type CompletionStatus = { 'notStarted' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface ContentInput {
  'title' : string,
  'subjects' : bigint,
  'order' : bigint,
  'difficulty' : DifficultyLevel,
  'description' : string,
  'classId' : bigint,
  'durationMinutes' : bigint,
  'pdfUrl' : [] | [string],
  'questions' : Array<Question>,
  'videoUrl' : [] | [string],
  'textContent' : [] | [string],
}
export type DifficultyLevel = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface NationTime { 'createdAt' : bigint, 'updatedAt' : bigint }
export type ProfileType = { 'teacher' : null } |
  { 'student' : null } |
  { 'parent' : null };
export interface Question {
  'marks' : [] | [bigint],
  'status' : ResourceStatus,
  'topic' : bigint,
  'difficulty' : [] | [DifficultyLevel],
  'explanation' : [] | [string],
  'createdAt' : NationTime,
  'text' : string,
  'correctAnswer' : bigint,
  'questionType' : QuestionType,
  'updatedAt' : NationTime,
  'questionId' : bigint,
  'options' : Array<string>,
}
export type QuestionType = { 'shortAnswer' : null } |
  { 'fillInTheBlanks' : null } |
  { 'multipleChoice' : null } |
  { 'trueFalse' : null };
export type ResourceStatus = { 'deleted' : null } |
  { 'active' : null } |
  { 'inactive' : null } |
  { 'archived' : null };
export interface StudentProfile {
  'id' : bigint,
  'timezone' : string,
  'grades' : string,
  'country' : string,
  'subjects' : Array<string>,
  'displayName' : string,
  'birthdate' : string,
  'city' : string,
  'userId' : Principal,
  'joinedAt' : bigint,
  'profileID' : string,
  'photoURL' : string,
  'classId' : bigint,
  'email' : string,
  'languagePref' : string,
  'updatedAt' : bigint,
  'state' : string,
  'entrySource' : string,
  'gender' : string,
  'phone' : string,
  'parentID' : string,
  'profileType' : ProfileType,
  'deletedAt' : bigint,
  'medium' : string,
}
export interface Topic {
  'id' : bigint,
  'status' : ResourceStatus,
  'title' : string,
  'order' : [] | [bigint],
  'difficulty' : [] | [DifficultyLevel],
  'createdAt' : NationTime,
  'description' : [] | [string],
  'chapterId' : bigint,
  'classId' : [] | [bigint],
  'updatedAt' : NationTime,
  'durationMinutes' : [] | [bigint],
  'subjectId' : bigint,
  'pdfUrl' : [] | [string],
  'questions' : Array<Question>,
  'videoUrl' : [] | [string],
  'textContent' : [] | [string],
}
export interface TopicProgressEntry {
  'id' : bigint,
  'timeSpentSeconds' : bigint,
  'studentId' : bigint,
  'completionStatus' : CompletionStatus,
  'createdAt' : NationTime,
  'attempts' : bigint,
  'score' : bigint,
  'updatedAt' : NationTime,
  'correctAnswers' : bigint,
  'topicId' : bigint,
}
export interface UserProfile {
  'displayName' : string,
  'classId' : string,
  'languagePref' : string,
  'medium' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createChapter' : ActorMethod<
    [bigint, bigint, string, [] | [string], [] | [bigint]],
    bigint
  >,
  'createStudentProfile' : ActorMethod<
    [string, bigint, string, string],
    bigint
  >,
  'createTopic' : ActorMethod<[ContentInput], bigint>,
  'deleteChapter' : ActorMethod<[bigint], undefined>,
  'deleteTopic' : ActorMethod<[bigint], undefined>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllChapters' : ActorMethod<[], Array<Chapter>>,
  'getAllClasses' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChaptersForSubject' : ActorMethod<[bigint, bigint], Array<Chapter>>,
  'getMyProgress' : ActorMethod<[], Array<TopicProgressEntry>>,
  'getMyStudentProfile' : ActorMethod<[], [] | [StudentProfile]>,
  'getStudentProfile' : ActorMethod<[Principal], [] | [StudentProfile]>,
  'getStudentProgress' : ActorMethod<[Principal], Array<TopicProgressEntry>>,
  'getTopicsForChapter' : ActorMethod<[bigint, bigint, bigint], Array<Topic>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllStudents' : ActorMethod<[], Array<StudentProfile>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateChapter' : ActorMethod<
    [bigint, bigint, bigint, string, [] | [string], [] | [bigint]],
    undefined
  >,
  'updateStudentProfile' : ActorMethod<
    [string, bigint, string, string],
    undefined
  >,
  'updateTopic' : ActorMethod<[bigint, ContentInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];