/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface TopicProgressEntry {
    id: bigint;
    timeSpentSeconds: bigint;
    studentId: bigint;
    completionStatus: CompletionStatus;
    createdAt: NationTime;
    attempts: bigint;
    score: bigint;
    updatedAt: NationTime;
    correctAnswers: bigint;
    topicId: bigint;
}
export interface ContentInput {
    title: string;
    subjects: bigint;
    order: bigint;
    difficulty: DifficultyLevel;
    description: string;
    classId: bigint;
    durationMinutes: bigint;
    pdfUrl?: string;
    questions: Array<Question>;
    videoUrl?: string;
    textContent?: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Chapter {
    id: bigint;
    status: ResourceStatus;
    title: string;
    order?: bigint;
    icon?: string;
    createdAt: NationTime;
    classId?: bigint;
    updatedAt: NationTime;
    subjectId: bigint;
}
export interface StudentProfile {
    id: bigint;
    timezone: string;
    grades: string;
    country: string;
    subjects: Array<string>;
    displayName: string;
    birthdate: string;
    city: string;
    userId: Principal;
    joinedAt: bigint;
    profileID: string;
    photoURL: string;
    classId: bigint;
    email: string;
    languagePref: string;
    updatedAt: bigint;
    state: string;
    entrySource: string;
    gender: string;
    phone: string;
    parentID: string;
    profileType: ProfileType;
    deletedAt: bigint;
    medium: string;
}
export interface AdminStats {
    topicsCompletedTotal: bigint;
    totalStudents: bigint;
    activeToday: bigint;
}
export interface Topic {
    id: bigint;
    status: ResourceStatus;
    title: string;
    order?: bigint;
    difficulty?: DifficultyLevel;
    createdAt: NationTime;
    description?: string;
    chapterId: bigint;
    classId?: bigint;
    updatedAt: NationTime;
    durationMinutes?: bigint;
    subjectId: bigint;
    pdfUrl?: string;
    questions: Array<Question>;
    videoUrl?: string;
    textContent?: string;
}
export interface NationTime {
    createdAt: bigint;
    updatedAt: bigint;
}
export interface Question {
    marks?: bigint;
    status: ResourceStatus;
    topic: bigint;
    difficulty?: DifficultyLevel;
    explanation?: string;
    createdAt: NationTime;
    text: string;
    correctAnswer: bigint;
    questionType: QuestionType;
    updatedAt: NationTime;
    questionId: bigint;
    options: Array<string>;
}
export interface UserProfile {
    displayName: string;
    classId: string;
    languagePref: string;
    medium: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum CompletionStatus {
    notStarted = "notStarted",
    completed = "completed",
    inProgress = "inProgress"
}
export enum DifficultyLevel {
    easy = "easy",
    hard = "hard",
    medium = "medium"
}
export enum ProfileType {
    teacher = "teacher",
    student = "student",
    parent = "parent"
}
export enum QuestionType {
    shortAnswer = "shortAnswer",
    fillInTheBlanks = "fillInTheBlanks",
    multipleChoice = "multipleChoice",
    trueFalse = "trueFalse"
}
export enum ResourceStatus {
    deleted = "deleted",
    active = "active",
    inactive = "inactive",
    archived = "archived"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createChapter(classId: bigint, subjectId: bigint, title: string, icon: string | null, order: bigint | null): Promise<bigint>;
    createStudentProfile(displayName: string, classId: bigint, medium: string, languagePref: string): Promise<bigint>;
    createTopic(content: ContentInput): Promise<bigint>;
    deleteChapter(id: bigint): Promise<void>;
    deleteTopic(topicId: bigint): Promise<void>;
    getAdminStats(): Promise<AdminStats>;
    getAllChapters(): Promise<Array<Chapter>>;
    getAllClasses(): Promise<Array<string>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChaptersForSubject(subjectId: bigint, classId: bigint): Promise<Array<Chapter>>;
    getMyProgress(): Promise<Array<TopicProgressEntry>>;
    getMyStudentProfile(): Promise<StudentProfile | null>;
    getStudentProfile(studentPrincipal: Principal): Promise<StudentProfile | null>;
    getStudentProgress(studentPrincipal: Principal): Promise<Array<TopicProgressEntry>>;
    getTopicsForChapter(chapterId: bigint, subjectId: bigint, classId: bigint): Promise<Array<Topic>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllStudents(): Promise<Array<StudentProfile>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateChapter(chapterId: bigint, classId: bigint, subjectId: bigint, title: string, icon: string | null, order: bigint | null): Promise<void>;
    updateStudentProfile(displayName: string, classId: bigint, medium: string, languagePref: string): Promise<void>;
    updateTopic(topicId: bigint, content: ContentInput): Promise<void>;
}
import type { Chapter as _Chapter, CompletionStatus as _CompletionStatus, ContentInput as _ContentInput, DifficultyLevel as _DifficultyLevel, NationTime as _NationTime, ProfileType as _ProfileType, Question as _Question, QuestionType as _QuestionType, ResourceStatus as _ResourceStatus, StudentProfile as _StudentProfile, Topic as _Topic, TopicProgressEntry as _TopicProgressEntry, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createChapter(arg0: bigint, arg1: bigint, arg2: string, arg3: string | null, arg4: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createChapter(arg0, arg1, arg2, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChapter(arg0, arg1, arg2, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async createStudentProfile(arg0: string, arg1: bigint, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudentProfile(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudentProfile(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createTopic(arg0: ContentInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTopic(to_candid_ContentInput_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTopic(to_candid_ContentInput_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteChapter(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChapter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChapter(arg0);
            return result;
        }
    }
    async deleteTopic(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTopic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTopic(arg0);
            return result;
        }
    }
    async getAdminStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getAllChapters(): Promise<Array<Chapter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChapters();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChapters();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllClasses(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClasses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClasses();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChaptersForSubject(arg0: bigint, arg1: bigint): Promise<Array<Chapter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChaptersForSubject(arg0, arg1);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChaptersForSubject(arg0, arg1);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProgress(): Promise<Array<TopicProgressEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProgress();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProgress();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyStudentProfile(): Promise<StudentProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyStudentProfile();
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyStudentProfile();
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentProfile(arg0: Principal): Promise<StudentProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentProfile(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentProfile(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentProgress(arg0: Principal): Promise<Array<TopicProgressEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentProgress(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentProgress(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopicsForChapter(arg0: bigint, arg1: bigint, arg2: bigint): Promise<Array<Topic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopicsForChapter(arg0, arg1, arg2);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopicsForChapter(arg0, arg1, arg2);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllStudents(): Promise<Array<StudentProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllStudents();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllStudents();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateChapter(arg0: bigint, arg1: bigint, arg2: bigint, arg3: string, arg4: string | null, arg5: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChapter(arg0, arg1, arg2, arg3, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChapter(arg0, arg1, arg2, arg3, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateStudentProfile(arg0: string, arg1: bigint, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudentProfile(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudentProfile(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateTopic(arg0: bigint, arg1: ContentInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTopic(arg0, to_candid_ContentInput_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTopic(arg0, to_candid_ContentInput_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Chapter_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Chapter): Chapter {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_CompletionStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompletionStatus): CompletionStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_DifficultyLevel_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DifficultyLevel): DifficultyLevel {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_ProfileType_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfileType): ProfileType {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionType_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionType): QuestionType {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_ResourceStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResourceStatus): ResourceStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_StudentProfile_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentProfile): StudentProfile {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_TopicProgressEntry_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TopicProgressEntry): TopicProgressEntry {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Topic_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Topic): Topic {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentProfile]): StudentProfile | null {
    return value.length === 0 ? null : from_candid_StudentProfile_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DifficultyLevel]): DifficultyLevel | null {
    return value.length === 0 ? null : from_candid_DifficultyLevel_n46(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ResourceStatus;
    title: string;
    order: [] | [bigint];
    icon: [] | [string];
    createdAt: _NationTime;
    classId: [] | [bigint];
    updatedAt: _NationTime;
    subjectId: bigint;
}): {
    id: bigint;
    status: ResourceStatus;
    title: string;
    order?: bigint;
    icon?: string;
    createdAt: NationTime;
    classId?: bigint;
    updatedAt: NationTime;
    subjectId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ResourceStatus_n26(_uploadFile, _downloadFile, value.status),
        title: value.title,
        order: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.order)),
        icon: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.icon)),
        createdAt: value.createdAt,
        classId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.classId)),
        updatedAt: value.updatedAt,
        subjectId: value.subjectId
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    timeSpentSeconds: bigint;
    studentId: bigint;
    completionStatus: _CompletionStatus;
    createdAt: _NationTime;
    attempts: bigint;
    score: bigint;
    updatedAt: _NationTime;
    correctAnswers: bigint;
    topicId: bigint;
}): {
    id: bigint;
    timeSpentSeconds: bigint;
    studentId: bigint;
    completionStatus: CompletionStatus;
    createdAt: NationTime;
    attempts: bigint;
    score: bigint;
    updatedAt: NationTime;
    correctAnswers: bigint;
    topicId: bigint;
} {
    return {
        id: value.id,
        timeSpentSeconds: value.timeSpentSeconds,
        studentId: value.studentId,
        completionStatus: from_candid_CompletionStatus_n35(_uploadFile, _downloadFile, value.completionStatus),
        createdAt: value.createdAt,
        attempts: value.attempts,
        score: value.score,
        updatedAt: value.updatedAt,
        correctAnswers: value.correctAnswers,
        topicId: value.topicId
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    timezone: string;
    grades: string;
    country: string;
    subjects: Array<string>;
    displayName: string;
    birthdate: string;
    city: string;
    userId: Principal;
    joinedAt: bigint;
    profileID: string;
    photoURL: string;
    classId: bigint;
    email: string;
    languagePref: string;
    updatedAt: bigint;
    state: string;
    entrySource: string;
    gender: string;
    phone: string;
    parentID: string;
    profileType: _ProfileType;
    deletedAt: bigint;
    medium: string;
}): {
    id: bigint;
    timezone: string;
    grades: string;
    country: string;
    subjects: Array<string>;
    displayName: string;
    birthdate: string;
    city: string;
    userId: Principal;
    joinedAt: bigint;
    profileID: string;
    photoURL: string;
    classId: bigint;
    email: string;
    languagePref: string;
    updatedAt: bigint;
    state: string;
    entrySource: string;
    gender: string;
    phone: string;
    parentID: string;
    profileType: ProfileType;
    deletedAt: bigint;
    medium: string;
} {
    return {
        id: value.id,
        timezone: value.timezone,
        grades: value.grades,
        country: value.country,
        subjects: value.subjects,
        displayName: value.displayName,
        birthdate: value.birthdate,
        city: value.city,
        userId: value.userId,
        joinedAt: value.joinedAt,
        profileID: value.profileID,
        photoURL: value.photoURL,
        classId: value.classId,
        email: value.email,
        languagePref: value.languagePref,
        updatedAt: value.updatedAt,
        state: value.state,
        entrySource: value.entrySource,
        gender: value.gender,
        phone: value.phone,
        parentID: value.parentID,
        profileType: from_candid_ProfileType_n40(_uploadFile, _downloadFile, value.profileType),
        deletedAt: value.deletedAt,
        medium: value.medium
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ResourceStatus;
    title: string;
    order: [] | [bigint];
    difficulty: [] | [_DifficultyLevel];
    createdAt: _NationTime;
    description: [] | [string];
    chapterId: bigint;
    classId: [] | [bigint];
    updatedAt: _NationTime;
    durationMinutes: [] | [bigint];
    subjectId: bigint;
    pdfUrl: [] | [string];
    questions: Array<_Question>;
    videoUrl: [] | [string];
    textContent: [] | [string];
}): {
    id: bigint;
    status: ResourceStatus;
    title: string;
    order?: bigint;
    difficulty?: DifficultyLevel;
    createdAt: NationTime;
    description?: string;
    chapterId: bigint;
    classId?: bigint;
    updatedAt: NationTime;
    durationMinutes?: bigint;
    subjectId: bigint;
    pdfUrl?: string;
    questions: Array<Question>;
    videoUrl?: string;
    textContent?: string;
} {
    return {
        id: value.id,
        status: from_candid_ResourceStatus_n26(_uploadFile, _downloadFile, value.status),
        title: value.title,
        order: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.order)),
        difficulty: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.difficulty)),
        createdAt: value.createdAt,
        description: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.description)),
        chapterId: value.chapterId,
        classId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.classId)),
        updatedAt: value.updatedAt,
        durationMinutes: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.durationMinutes)),
        subjectId: value.subjectId,
        pdfUrl: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.pdfUrl)),
        questions: from_candid_vec_n48(_uploadFile, _downloadFile, value.questions),
        videoUrl: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.videoUrl)),
        textContent: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.textContent))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    marks: [] | [bigint];
    status: _ResourceStatus;
    topic: bigint;
    difficulty: [] | [_DifficultyLevel];
    explanation: [] | [string];
    createdAt: _NationTime;
    text: string;
    correctAnswer: bigint;
    questionType: _QuestionType;
    updatedAt: _NationTime;
    questionId: bigint;
    options: Array<string>;
}): {
    marks?: bigint;
    status: ResourceStatus;
    topic: bigint;
    difficulty?: DifficultyLevel;
    explanation?: string;
    createdAt: NationTime;
    text: string;
    correctAnswer: bigint;
    questionType: QuestionType;
    updatedAt: NationTime;
    questionId: bigint;
    options: Array<string>;
} {
    return {
        marks: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.marks)),
        status: from_candid_ResourceStatus_n26(_uploadFile, _downloadFile, value.status),
        topic: value.topic,
        difficulty: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.difficulty)),
        explanation: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.explanation)),
        createdAt: value.createdAt,
        text: value.text,
        correctAnswer: value.correctAnswer,
        questionType: from_candid_QuestionType_n51(_uploadFile, _downloadFile, value.questionType),
        updatedAt: value.updatedAt,
        questionId: value.questionId,
        options: value.options
    };
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deleted: null;
} | {
    active: null;
} | {
    inactive: null;
} | {
    archived: null;
}): ResourceStatus {
    return "deleted" in value ? ResourceStatus.deleted : "active" in value ? ResourceStatus.active : "inactive" in value ? ResourceStatus.inactive : "archived" in value ? ResourceStatus.archived : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notStarted: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): CompletionStatus {
    return "notStarted" in value ? CompletionStatus.notStarted : "completed" in value ? CompletionStatus.completed : "inProgress" in value ? CompletionStatus.inProgress : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    teacher: null;
} | {
    student: null;
} | {
    parent: null;
}): ProfileType {
    return "teacher" in value ? ProfileType.teacher : "student" in value ? ProfileType.student : "parent" in value ? ProfileType.parent : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
}): DifficultyLevel {
    return "easy" in value ? DifficultyLevel.easy : "hard" in value ? DifficultyLevel.hard : "medium" in value ? DifficultyLevel.medium : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shortAnswer: null;
} | {
    fillInTheBlanks: null;
} | {
    multipleChoice: null;
} | {
    trueFalse: null;
}): QuestionType {
    return "shortAnswer" in value ? QuestionType.shortAnswer : "fillInTheBlanks" in value ? QuestionType.fillInTheBlanks : "multipleChoice" in value ? QuestionType.multipleChoice : "trueFalse" in value ? QuestionType.trueFalse : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Chapter>): Array<Chapter> {
    return value.map((x)=>from_candid_Chapter_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TopicProgressEntry>): Array<TopicProgressEntry> {
    return value.map((x)=>from_candid_TopicProgressEntry_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Topic>): Array<Topic> {
    return value.map((x)=>from_candid_Topic_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n49(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudentProfile>): Array<StudentProfile> {
    return value.map((x)=>from_candid_StudentProfile_n38(_uploadFile, _downloadFile, x));
}
function to_candid_ContentInput_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentInput): _ContentInput {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_DifficultyLevel_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DifficultyLevel): _DifficultyLevel {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_QuestionType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionType): _QuestionType {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_Question_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Question): _Question {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_ResourceStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceStatus): _ResourceStatus {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    subjects: bigint;
    order: bigint;
    difficulty: DifficultyLevel;
    description: string;
    classId: bigint;
    durationMinutes: bigint;
    pdfUrl?: string;
    questions: Array<Question>;
    videoUrl?: string;
    textContent?: string;
}): {
    title: string;
    subjects: bigint;
    order: bigint;
    difficulty: _DifficultyLevel;
    description: string;
    classId: bigint;
    durationMinutes: bigint;
    pdfUrl: [] | [string];
    questions: Array<_Question>;
    videoUrl: [] | [string];
    textContent: [] | [string];
} {
    return {
        title: value.title,
        subjects: value.subjects,
        order: value.order,
        difficulty: to_candid_DifficultyLevel_n14(_uploadFile, _downloadFile, value.difficulty),
        description: value.description,
        classId: value.classId,
        durationMinutes: value.durationMinutes,
        pdfUrl: value.pdfUrl ? candid_some(value.pdfUrl) : candid_none(),
        questions: to_candid_vec_n16(_uploadFile, _downloadFile, value.questions),
        videoUrl: value.videoUrl ? candid_some(value.videoUrl) : candid_none(),
        textContent: value.textContent ? candid_some(value.textContent) : candid_none()
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    marks?: bigint;
    status: ResourceStatus;
    topic: bigint;
    difficulty?: DifficultyLevel;
    explanation?: string;
    createdAt: NationTime;
    text: string;
    correctAnswer: bigint;
    questionType: QuestionType;
    updatedAt: NationTime;
    questionId: bigint;
    options: Array<string>;
}): {
    marks: [] | [bigint];
    status: _ResourceStatus;
    topic: bigint;
    difficulty: [] | [_DifficultyLevel];
    explanation: [] | [string];
    createdAt: _NationTime;
    text: string;
    correctAnswer: bigint;
    questionType: _QuestionType;
    updatedAt: _NationTime;
    questionId: bigint;
    options: Array<string>;
} {
    return {
        marks: value.marks ? candid_some(value.marks) : candid_none(),
        status: to_candid_ResourceStatus_n19(_uploadFile, _downloadFile, value.status),
        topic: value.topic,
        difficulty: value.difficulty ? candid_some(to_candid_DifficultyLevel_n14(_uploadFile, _downloadFile, value.difficulty)) : candid_none(),
        explanation: value.explanation ? candid_some(value.explanation) : candid_none(),
        createdAt: value.createdAt,
        text: value.text,
        correctAnswer: value.correctAnswer,
        questionType: to_candid_QuestionType_n21(_uploadFile, _downloadFile, value.questionType),
        updatedAt: value.updatedAt,
        questionId: value.questionId,
        options: value.options
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DifficultyLevel): {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
} {
    return value == DifficultyLevel.easy ? {
        easy: null
    } : value == DifficultyLevel.hard ? {
        hard: null
    } : value == DifficultyLevel.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceStatus): {
    deleted: null;
} | {
    active: null;
} | {
    inactive: null;
} | {
    archived: null;
} {
    return value == ResourceStatus.deleted ? {
        deleted: null
    } : value == ResourceStatus.active ? {
        active: null
    } : value == ResourceStatus.inactive ? {
        inactive: null
    } : value == ResourceStatus.archived ? {
        archived: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionType): {
    shortAnswer: null;
} | {
    fillInTheBlanks: null;
} | {
    multipleChoice: null;
} | {
    trueFalse: null;
} {
    return value == QuestionType.shortAnswer ? {
        shortAnswer: null
    } : value == QuestionType.fillInTheBlanks ? {
        fillInTheBlanks: null
    } : value == QuestionType.multipleChoice ? {
        multipleChoice: null
    } : value == QuestionType.trueFalse ? {
        trueFalse: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Question>): Array<_Question> {
    return value.map((x)=>to_candid_Question_n17(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
